# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostname',
            name='role_type',
            field=models.ManyToManyField(blank=True, default=1, to='salt.Userprofile'),
        ),
    ]
