# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostname',
            name='kernel',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
